spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  access_token:
    expiration_time: 86400000
  refresh_token:
    expiration_time: 604800000
  secret: '{cipher}AQAFb+Zm/rVAdNBz504oSzOBeXo/Cn1Hznt1msxeqRJWcJhmx8cZYFg2e5/93fs7Otzx5qT70IN8/kSkQn3Gt0nGbCFiRBg1vgB15w9mxF4POvVBor/XM0ieuVmEBRSiWz/QkXp63wKnVSqNG0FN9PKI85RQPjEzw1lcMANuy5Fs9KQ8nT9hImZm5B9ZYZ/Y460Dtn4IyScRtRZlfPABu42Me3YUJXn0EqznIx0R1cB97rM4miYbEu2PFC8LU/teEQniDAAlV6nKfH8g7eA3nkh5Fq70rpshE5N5QuuxPEKk8IZrLurtSQLtTc5rIMnsqc5y76M4vpPZ4klWu4PQqxHA2OW4jgqwrUWcDl5A3G4tYbtlfelN7wa5oitpuunlDNw='

cloud:
  aws:
    credentials:
      accessKey: '{cipher}AQB1kXLJ5cq2OhNs3z6Rb8E/5BkpzCpby5O2MneTOtkB6mOevBaFCoE9wFfVd5zAEIS7qFLdskDO7BxarVVaTAajhXbmxpvU7xggozYIc4PfwfxK5YpHCON0bol5QqDPO00pXCtCAYYYOiWYejMfKiDaCzQgU8ZcZHzI2rv/j68XzUCvjGHXx09WyuTUacWRrHIi72f3LyasJtXjsShR3yyKFjgQa4CGVdzcVBF0R+f4dB490TxDBR8Eei47HT1ZK6yAS4ZGZAH/yEqN4uPtYMaUO4Hlgyixc0zLUBwiLd5BLvUv3FtTTx5tuDqInUNXIIn1bwf+pWX5DwVm+FauMm3I1mfNbknL0O0Zazj3UgBlMajnlXQZzpbvfC77kSEZo9wbtMDN1xYUrpjq7ypMpL1W'
      secretKey: '{cipher}AQAwH8ZxbItdrE94JTlzCrq6TSZiInGub78+dsVvG7TB49h3MgpDbFLPtZW7ELmgujPvP/2gKg6u+ci+6B5SnSZKVHa4p2z/rzdYTG0UFZ++Uk5jG0nkAEQ0KOHDn3UEyzlYhpdVU3sNMJERDBxVZ7dUx6sisw4BCXGh0zPoxIQ5eYBJvLTBQgFTDEvhhOW6/8gN7UC82Et1rDqkyqevZAmVQSFJKUcb9ssofaFsTioZTdx3LkgdvKyy6aPQR77EB1NEWKrjqstxTxcSpI/Z4zsmqZXEVSGWwHHRPSE2MH3U9txEqHPTRnxceEL7bLErbeFAXaanXc3W+Qnynedl7noiEU8b3WbdbfeNXpda7XEVvpajyf2sA4KJnHhXqa6pK+wIEJw4Ef2q5u0aC9kwXTtW9SsUNB8006fgudyRRttySg=='
    s3:
      bucket: study-service-image
      thumbnailBucket: study-service-image-resize
    region:
      static: ap-northeast-2
    stack:
      auto: false