spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: '{cipher}AQBin2GbtE+StsqgP4qWcWH3lng+rqp5MdbjG0J/RUq3zbn0FgyUojmdHZjjZIHaL09fIld+H/IQRYaRCe5FjPQYkU7NZqcHGZFGx6t+NM8EZSJ45rAFcf7+Tq2ig9tu46T4hxQ2GGjwXEBcgS3yJHVVOzSiBEPxemkf7amHhQPJOnuddDlKg1g2zEPo5/CvC5MVVfv/G8bbXbQFuSH/qBVgDApr+rclC6RM9jwYJubaK6/H+tcqRmSkVrE0KauGb7Zl50OK6yEWEWmBN6fhcUq0gAZ3J1zUDcohZLNhKT+qjAbHleND+d5yLLIBzy+ncz60Y1TvPQMLNTXUxrdkWRTjdx51HCuPcEfkvHyAvxvG4cWwu7zsOY727pjivLqT7Rw='
    password: '{cipher}AQA1SmajV59sCMHobZdDnq7Yxr+ZTgexxMx0KblITwgjRg+UeFXTwzAj5S/kDJ8boSnOs6Vzch/SMw7MFvsxP4uYz0S88M8rofYv3SKYvD9fyyS/oQlFZTJ6ReOCwtxoyIzVlFwmVpElmD1uHGXdbS2Fifz/1SpJ/TqX2QVYkP3Kj8zYcQtLc1/LEVlsBvBGT2vTMs94tXZTiavLab35bR9watC/sW/x4TZnKtkVYGG3W0XFrj+/kzSnz/DGofIEtlV/RYFEAtKfhPJUihzGv1hHWLfwl26Vcq5mUvNGxA0hEbSQJNaHd6rSDW4DM7FlH8BG5xHPqxhqObhtjC1eTo83djtXL/Iz3CAlQ3CbTKs1a2pCQ3OXFf5rCY3nUvZVu+o='

token:
  access_token:
    expiration_time: 86400000
  refresh_token:
    expiration_time: 604800000
  secret: '{cipher}AQAb/qjrpc5Z4fjfjWJKq6tiCXOOUbx/gbvIuM5mba/FBG8T5NncxAkynBIRbsOBCXRHOdJf7LM5AJzSXNYxkMH9tnhI8axfumWQ9nfu4v6Fh5PsFwyZKT3xBDQqHE4wkOmZS5/8WJ6AWfQPH3L5BsEk/hhkBlbdHanE3Kts49Wt4scyziqg6NnifhUYyBzQED9pqflrLl0DeDsTuJTkmkYmf/104S1j6UchaIOWxHR5D1aluWKFLqz8yEBZkY2NsT5s9ddLgGWcYqURjE2B7Bs6fT4P+hMCa+hVr/dri7TRfwln8OfRB7hwHdSxh8Smq/dEbKalDq8kXWrL6w+10afbsVMkIvVmiGFBi47kXgn6x4rZEE8j+RN8bX0Sj3XhfR4='

cloud:
  aws:
    credentials:
      accessKey: '{cipher}AQAo4PDUWPev8SE1mkTb7cCbbRkZRwgbWnUZM2dbVBkRPgHnJhfemjT5NjqG6aK4DBMxuPC1phyo44sTDHMiqMyDxPIE3WP3efILl3o7Ndr6zVj2wOWH8aCNec9kjLe804UccoKfiDLSlXDMOiNWWZykb4SKkNwD1y0As1FGi1U6EW2PkyE48t3ZxEH3iJRqWhOzCZVEwyRnyhP3qQWxZXRFHbPGQrNHuSkqUNFmZAExo2Xnr2QiEiaQVV5D+VgTxZTHMxyNxuNjdQNkPjauDd6LANe2J467Z325/SQcWTJBaioxO1Whq12knkicaiSTYHocJVZpV4keE4jIN9VMM4fLO4kmZn5C+9PafdImqk+0cj2KRQIOb8b45xRqD5DinUq7tPR+AEgGQAACbt3DKoE3'
      secretKey: '{cipher}AQCnbNdNszPkMxjVPX6BNJJvc//FlgujiIXt9aXfOaAVIZ399ee1fRrTxxtYtbt1F9iNXJaOcMpI3dZXf6jic3wLwuBP1+cLTRAj/tgKdMqbwhFsm8E2DJdFiG7KbTi42Wgyf5y9P+3CCq98YvuLcnBcptQBFLuAXTaA5AVb7/TyQCpso7F5qWLj472eVEsAaERmz/DwGEM8k9yrKoEU4oGtnZHxFaaAGW8AyT6JOEUgZF/tCzDFldRIfZuB0A5krMgZPrNAfZYAjeLMVEnJnS2ADibnKm0TB8OtSW40hB3RRIS5nfaHnnN4h2AomRgB2t779f3vYS/YpW6LAd5AC+wRbRQziZwrCXm1RCURPrykDDr2mlp0p6wASd4Q+FTXznPXHrZYEM11jYGmAvr8v8BkV3MbPK8Y+mJloBI3tn1Kpg=='
    s3:
      bucket: shareu-file
    region:
      static: ap-northeast-2
    stack:
      auto: false