spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.37.147.101:3306/map?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: '{cipher}AQAlJTTrDiOZxjoyRNjxE89vN03kRisd0vzcZnKEg6b6PEhajgCeg5qqyIdA+7uMGIlyHs/5b+b6HE4R03TrFiQh0+Iwj5tKjfu7QZtzN43KXegqQk8Lo5GjcP4tFwSp3H3W9qF+24hSW+3mBUqNXF5z6KREnlfcXVkM8ZsClx0RY80OeKHv1Ci1wglaXpvkXsBn+igfW1CPmAN4AN+G8L+tRMPxee2/KUcM4HSQ6WCZoQl1jd0JkZivDY9B1axtVFWrS7AK7RfBI4omVf5TSc1qUnJ4y4TP8PTRq8XrRjyE4ch3M2pypRYpdxnpuNwcw6IXGdoAP8pd/rfuyUhHKFAkweURW+B7IDVJl3ZhklV961OkAXKxLNGLWk0x1EP2/nc='
    password: ""

token:
  access_token:
    expiration_time: 86400000
  refresh_token:
    expiration_time: 604800000
  secret: '{cipher}AQAFb+Zm/rVAdNBz504oSzOBeXo/Cn1Hznt1msxeqRJWcJhmx8cZYFg2e5/93fs7Otzx5qT70IN8/kSkQn3Gt0nGbCFiRBg1vgB15w9mxF4POvVBor/XM0ieuVmEBRSiWz/QkXp63wKnVSqNG0FN9PKI85RQPjEzw1lcMANuy5Fs9KQ8nT9hImZm5B9ZYZ/Y460Dtn4IyScRtRZlfPABu42Me3YUJXn0EqznIx0R1cB97rM4miYbEu2PFC8LU/teEQniDAAlV6nKfH8g7eA3nkh5Fq70rpshE5N5QuuxPEKk8IZrLurtSQLtTc5rIMnsqc5y76M4vpPZ4klWu4PQqxHA2OW4jgqwrUWcDl5A3G4tYbtlfelN7wa5oitpuunlDNw='

cloud:
  aws:
    credentials:
      accessKey: '{cipher}AQBX9hdgIKRC/XMgdaW/WXUmHLj8NMZD7FDC95hOer2JhuJY8ST9gnodlofZOwbEEyswZbTnVx1yNXj1c0f2j9l60DP7bV8iEMWc9MG7uhqndy+qZf1+uj6+ReQbVItOuYIPfCkhE/Bx6v58qozenWjU2ERXVl+JPaiYgpv7vZSFv7R7rSl/bK7ss1/a2itFPWixzCyOGcG3MHgVKOU8kLxksvQeVciWmysRQ07nqCz2NOVq1peaJK9Sa13bVW7zAv5y0ALSzGrM+JOYpAyzq9ldwNbzZyswu76CaDMiL1YdsagWNorTHyHhJxLYi2HmYlf2rLT08aubV5/ocvMzqQsO5Ze5omaTAZRo8w5MF6zDlbE3uCCoemAJpTZMf90PVaEgUgMNr2cWYkkeW+WhTy53'
      secretKey: '{cipher}AQAj9Owm1ur3AMM/1WR76o+ceW8NBBunyunNXwPo1pk0N8V2T3RNAXK+zoB0FjPHXPVNLlq9oChpwjLoCT7M200OCQRpOOs4J0DyJ0+0B+3umWH1DgqwwQPZxLCEcF1AnxBy1fmj/TXm7ABql9PRIPenPOGwKvfaWRfss/NERGA6ON/+LL1nCuVgVKWXIspiPLuWGxrvc0zAjSFp4cBn4O41vY0S3CFcXSq4T8ZHjkZWm0fv2QVYxkS0M+xe3T6Fxe7mNErHmHd4SE+DhDn5whSRQ5PQOoDH0qvYfxU4lgbhZV6zQr9R7vxfH9r3fppaevUF3HPi3vs8QAWEWM97KdnbInB2mow7YgyDAbKDlTqEBed9Sx7QvFKGTJMjyFx74TwJWXEK5D/XS0KpidHm8rZ1inf6fLndCDp7IvMjUYkWhw=='
    s3:
      bucket: study-service-image
      thumbnailBucket: study-service-image-resize
    region:
      static: ap-northeast-2
    stack:
      auto: false