spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCLMl+XEQXU7hyMKRlE5v2C1YWWTdAQE/gdYZ+u0dX0rAfiSxJQVJsgJPZXlXEl1H7BFjPC9Vgqzrpat1NK3kzH8hB3eqVr9Z+8jeNjjMG2eWjsPNNuYJq43g3wYMEXbGLjzQ8GKhwWKFNny/wGJIOMeE1LX1v1Xm1cr43BtrftFjIMYTEKezz8QlUGRbjpJxiobmX8QcBXwy8ZnEAbfFmMq7j1gb8/DzWKn9ODMDz61I/giqJbhw+ZQdG2hQHxUZilbYH6iEUO/HHqsx5A8wNL+ydfhPGYx4YmCqM3OSsPoQBxJct8RInF9Fr8mIhASseVq1VPci87+m+8WkG3C9itUu0s/dTU9+OA582pIK9HKqENWuskrl4hnkJwuTZ/zd0='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBlpS5a5vxMk3X7xLNPQguIyqFWenGI3QOjkj6oTOVhQPuWtxOPZbGA4s+VOXsEZyeImBhRQG9bBE7aEbe6m9Jq1psIkg3ikQ/b1mAUKZkEupqVdeBfIzQjVf6TDqcdEEUtPrYLuUwVoD0UrhLs2UANrAvXRLFMdpYAYdrA/hVaKagYryZ074q00PU0cXT3V3Maoc/FE+nalXfEVMVfACN5tCXMUWbATDpzhy8W4ccOt72U1rmNTfAKURJxdxcOwkS19f56HEr32DS1fyd0kD8J8PkmQnt6ll8wtdUuXinfKyxuIu9b74slX+c+eyJMLFqgCSGUKyOYahKhjTo/A5WCWxV3aZQFoiV+z3uDxT+tuKxKDC4bG0FvFyEh4Mj51E0CnKoL9onF9XYqd359tsAO'

gateway:
  ip: 172.18.0.5

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    orders_is_empty: There is no item