spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  access_token:
    expiration_time: 86400000
  refresh_token:
    expiration_time: 604800000
  secret: '{cipher}AQAb/qjrpc5Z4fjfjWJKq6tiCXOOUbx/gbvIuM5mba/FBG8T5NncxAkynBIRbsOBCXRHOdJf7LM5AJzSXNYxkMH9tnhI8axfumWQ9nfu4v6Fh5PsFwyZKT3xBDQqHE4wkOmZS5/8WJ6AWfQPH3L5BsEk/hhkBlbdHanE3Kts49Wt4scyziqg6NnifhUYyBzQED9pqflrLl0DeDsTuJTkmkYmf/104S1j6UchaIOWxHR5D1aluWKFLqz8yEBZkY2NsT5s9ddLgGWcYqURjE2B7Bs6fT4P+hMCa+hVr/dri7TRfwln8OfRB7hwHdSxh8Smq/dEbKalDq8kXWrL6w+10afbsVMkIvVmiGFBi47kXgn6x4rZEE8j+RN8bX0Sj3XhfR4='

cloud:
  aws:
    credentials:
      accessKey: '{cipher}AQAo4PDUWPev8SE1mkTb7cCbbRkZRwgbWnUZM2dbVBkRPgHnJhfemjT5NjqG6aK4DBMxuPC1phyo44sTDHMiqMyDxPIE3WP3efILl3o7Ndr6zVj2wOWH8aCNec9kjLe804UccoKfiDLSlXDMOiNWWZykb4SKkNwD1y0As1FGi1U6EW2PkyE48t3ZxEH3iJRqWhOzCZVEwyRnyhP3qQWxZXRFHbPGQrNHuSkqUNFmZAExo2Xnr2QiEiaQVV5D+VgTxZTHMxyNxuNjdQNkPjauDd6LANe2J467Z325/SQcWTJBaioxO1Whq12knkicaiSTYHocJVZpV4keE4jIN9VMM4fLO4kmZn5C+9PafdImqk+0cj2KRQIOb8b45xRqD5DinUq7tPR+AEgGQAACbt3DKoE3'
      secretKey: '{cipher}AQCnbNdNszPkMxjVPX6BNJJvc//FlgujiIXt9aXfOaAVIZ399ee1fRrTxxtYtbt1F9iNXJaOcMpI3dZXf6jic3wLwuBP1+cLTRAj/tgKdMqbwhFsm8E2DJdFiG7KbTi42Wgyf5y9P+3CCq98YvuLcnBcptQBFLuAXTaA5AVb7/TyQCpso7F5qWLj472eVEsAaERmz/DwGEM8k9yrKoEU4oGtnZHxFaaAGW8AyT6JOEUgZF/tCzDFldRIfZuB0A5krMgZPrNAfZYAjeLMVEnJnS2ADibnKm0TB8OtSW40hB3RRIS5nfaHnnN4h2AomRgB2t779f3vYS/YpW6LAd5AC+wRbRQziZwrCXm1RCURPrykDDr2mlp0p6wASd4Q+FTXznPXHrZYEM11jYGmAvr8v8BkV3MbPK8Y+mJloBI3tn1Kpg=='
    s3:
      bucket: shareu-file
    region:
      static: ap-northeast-2
    stack:
      auto: false